[versions]
agp = "9.3.0"
kotlin = "2.4.10"
xposedApi = "102.0.0"
androidxAppcompat = "1.7.0"
androidxActivityCompose = "1.13.0"
miuix = "0.9.3"
androidxDynamicAnimation = "1.1.0"

[plugins]
agpApp = { id = "com.android.application", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "xposedApi" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
miuix-ui = { group = "top.yukonga.miuix.kmp", name = "miuix-ui", version.ref = "miuix" }
miuix-preference = { group = "top.yukonga.miuix.kmp", name = "miuix-preference", version.ref = "miuix" }
miuix-icons = { group = "top.yukonga.miuix.kmp", name = "miuix-icons", version.ref = "miuix" }
androidx-dynamicanimation = { group = "androidx.dynamicanimation", name = "dynamicanimation", version.ref = "androidxDynamicAnimation" }
